#!/bin/bash

set -e -u -x

root="$(cd $(dirname $0) && pwd)"

for repo in repos/*; do
  pushd $repo
    if ! [ -f NOTICE.md ]; then
      echo "WARNING: $repo did not have NOTICE.md before!"
    fi

    "$root/generate-notice"
  popd
done
