#!/bin/bash

set -e -u -x

START_YEAR=$(git show --quiet $(git rev-list --max-parents=0 HEAD) --format="format:%ad" --date="format:%Y" | sort | head -1)
END_YEAR=$(git show --quiet HEAD --format="format:%ad" --date="format:%Y" | sort -r | head -1)

function abort() {
  echo "$@" >&2
  exit 1
}

[ -z "$START_YEAR" ] && abort "failed to determine start date"
[ -z "$END_YEAR" ] && abort "failed to determine end date"

RANGE=""
if [ "$START_YEAR" = "$END_YEAR" ]; then
  RANGE="$START_YEAR"
else
  RANGE="${START_YEAR}-${END_YEAR}"
fi

git checkout master

git pull --ff-only

action=""
if [ -e NOTICE.md ]; then
  action="update"
else
  action="create"
fi

cat > NOTICE.md <<EOF
Copyright $RANGE Alex Suraci, Chris Brown, and Pivotal Software, Inc.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
EOF

git add NOTICE.md

git commit -m "$action NOTICE.md"
